### ISSUE TITLE
Plan list

### ISSUE THREAD

**Issue by dinboyko** [wanunulab/ioniq#14]
1. Write documentation in Sphinx style.
2.  **Pylint** requires many changes in the code, including those that can change the behavior of the program (i.e., change self to cls, adding super().__init__() to instance initialization…). Run the lints with Ali to work on the major functions. This will help determine the disable commands for pylint actions.
4. **Pull request after cleaning Pylint**?
5. Finish the test files (if needed).
6. Upload test files for the pytest actions.
7. Write the .opt file reader.

**Comment by a-fa** [comment]
eliminate main.py, there is no main in this package. regarding other plans, see the drafts of stuff in project and pay attention to their priority orders.

**Comment by dinboyko** [comment]
got it, ty
