### ISSUE TITLE
Requirements.txt packages aren't installed when you pip install ioniq. 

### ISSUE THREAD

**Issue by a-fa** [wanunulab/ioniq#19]
in setup.py there is no mention of requirements.txt . setup.py or its future counterpart pyproject.toml should define how a package is installed, you shouldn't have to pip install -r 'requirements.txt' separately. 

Also all pytests are mistakenly referencing the actual python files through sys.path trickery, not the "installed module". 

The point of setup.py / pyproject.toml is to allow the package to become importable no matter where the cwd is. it is supposed to be a real installation. 

We want pytest to install this package (just like the user would), not just the packages contained in the requirements.txt file.

**Comment by dinboyko** [comment]
I moved requirements.txt to pyproject.toml
