### ISSUE TITLE
Test every file, call all functions, and ensure no import errors remain. Once done, mark the milestone as complete.

### ISSUE THREAD

**Issue by a-fa** [wanunulab/ioniq#8]

**Comment by a-fa** [comment]
The code may be buggy, we just want to make sure the imports are good and we are not working with any deprecated apis.

**Comment by dinboyko** [comment]
Working on testing io.py

**Comment by dinboyko** [comment]
Can't add the test files... 
<img width="1054" alt="Screenshot 2024-10-05 at 12 22 05 AM" src="https://github.com/user-attachments/assets/0fcd4ab0-b358-4469-86b6-21053c307502">

**Comment by a-fa** [comment]
@dinboyko Please be more descriptive. test files cannot be added to what?

**Comment by dinboyko** [comment]
@a-fa my bad, I was doing a very wrong and stupid thing. I was trying to push from main, and the new files were deleted when I checked back to the feature. I recovered  and pushed the test modules
